# Site settings
title: Fei Yin
name: Fei Yin
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/lucafei
#Any buzzword skills you want to include
skills:
 - C++
 - Python
 - Java
 - Matlab/Simulink
 - Pytorch
 - ROS
 - Latex, Microsoft Office Software
#Work experience is required
roles:
 - title: 
   start: 
   end: 
   employer: 
   description: 
#Education is required
education:
 - level: Bachelor of Engineering (B.Eng.)
   date: 
   subject: 
   school: 
 - level: Bachelor of Engineering (B.Eng.)
   date: 
   subject: 
   school: 
 - level: Master of Science (M.S.)
   date: 
   subject: 
   school:
#List of interesting Github repo/projects to include - optional
github:
 - robhinds/twitter-sentiment-analysis
 - robhinds/spring-reactor-twitter
 - robhinds/microservices
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot
